requirements.txt: update the need sqlalchemy version to 1.3.12 and above.
When the SQLAlchemy version is less than 1.3.11, there is an error like
this `File "/usr/local/lib/python3.6/site-packages/alembic/ddl/sqlite.py",
line 56, in requires_recreate_in_batch and col.server_default.persisted
AttributeError: 'NoneType' object has no attribute 'persisted'`

The sqlalchemy/alembic repo fix compat issue with older SQLAlchemy
versions in
https://github.com/sqlalchemy/alembic/commit/2866272251637c0dd246c275cf04947849ea88b8
and point the issue is caused by the lower SQLAlchemy version (less than
SQLAlchemy 1.3.11)

so it's better for us to update the need SQLAlchemy version from 1.3 to
1.3.12 or update the need alembic version from 1.1.0 to 1.11.0.
Obviouly,  update the need sqlalchemy version to 1.3.12 and
above is better than update the need alembic version to 1.11.0.

Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>