ima_emulator: specify sys.argv as the named parameter argv in main()
Fixes the following issue, which followed-up from b0dcaa8:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_ima_emulator", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_ima_emulator')())
TypeError: main() missing 1 required positional argument: 'argv'

Other utilities under cmd/ also use this approach.

Signed-off-by: Sergio Correia <scorreia@redhat.com>