codestyle: Add missing type parameter to generic type 'Pattern' (mypy)
Fix the following issue detected by mypy:

keylime/mba/elchecking/tests.py:460: error: Missing type parameters for generic type "Pattern"  [type-arg]

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>