Fix evictcontrol for tpm2 tools 3.2
It appears that for tpm2-tools 3.2 the tpm2_evictcontrol accepts
handle from the -H argument instead of -c.

  # tpm2_evictcontrol -A o -c 0x81010007 -P keylime
  ERROR: Invalid arguments
  ERROR: Unable to run tpm2_evictcontrol

Suddenly hits this issue in a working host.

Signed-off-by: Kaifeng Wang <kaifeng.w@gmail.com>