Fix response handling in tenant
Response object from requests doesn't have status attribute,
some code path will hit this:

AttributeError: 'Response' object has no attribute 'status'

Response doesn't have read() method either, changed to use text
attribute.

Signed-off-by: Kaifeng Wang <kaifeng.w@gmail.com>