migrations: Move bind parameter from MetaData() to reflect() method
Move the bind parameter from MetaData() constructor to reflect()
method. This helps resolve this type of issues detected by pylint
probably due to the deprecated bind parameter in MetaData().

keylime/migrations/versions/8c0f8ded1f90_convert_allowlists_to_ima_policies.py:47:11: E1123: Unexpected keyword argument 'bind' in constructor call (unexpected-keyword-arg)
keylime/migrations/versions/8c0f8ded1f90_convert_allowlists_to_ima_policies.py:48:4: E1120: No value for argument 'bind' in method call (no-value-for-parameter)

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>