ima: Fix runtime error due to wrong datatype
Fix the following runtime bug by using path.name rather than path

2021-07-15 14:02:16.943 - keylime.cloudverifier - ERROR - expected string or bytes-like object
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime/cloud_verifier_tornado.py", line 654, in invoke_get_quote
    if cloud_verifier_common.process_quote_response(agent, json_response['results'], agentAttestState):
  File "/usr/local/lib/python3.9/site-packages/keylime/cloud_verifier_common.py", line 219, in process_quote_response
    validQuote = get_tpm_instance().check_quote(
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 1100, in check_quote
    return self.check_pcrs(agentAttestState, tpm_policy, pcrs, data, False, ima_measurement_list, allowlist, ima_keyring, mb_measurement_list, mb_refstate)
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_abstract.py", line 264, in check_pcrs
    if self.__check_ima(agentAttestState, pcrval, ima_measurement_list, allowlist, ima_keyring):
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_abstract.py", line 210, in __check_ima
    ex_value = ima.process_measurement_list(agentAttestState, ima_measurement_list.split('\n'), allowlist, pcrval=pcrval, ima_keyring=ima_keyring)
  File "/usr/local/lib/python3.9/site-packages/keylime/ima.py", line 211, in process_measurement_list
    result = _process_measurement_list(agentAttestState, lines, lists=lists, m2w=m2w, pcrval=pcrval, ima_keyring=ima_keyring)
  File "/usr/local/lib/python3.9/site-packages/keylime/ima.py", line 167, in _process_measurement_list
    if not entry.valid():
  File "/usr/local/lib/python3.9/site-packages/keylime/ima_ast.py", line 318, in valid
    return self.mode.is_data_valid(self.validator)
  File "/usr/local/lib/python3.9/site-packages/keylime/ima_ast.py", line 242, in is_data_valid
    return validator.get_validator(type(self))(self.digest, self.path, self.signature)
  File "/usr/local/lib/python3.9/site-packages/keylime/ima.py", line 104, in _validate_ima_sig
    if exclude_regex is not None and exclude_regex.match(path):
TypeError: expected string or bytes-like object

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>