tests: Split unittests into two runs to avoid issue
Split unittests into two runs since one unittest in discover mode
would lead to the following error related to jsonschema:

ImportError: Failed to import test module: ima.ima_test
Traceback (most recent call last):
  File "/usr/lib64/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/__w/keylime/keylime/keylime/ima/ima_test.py", line 4, in <module>
    from keylime.ima import ima
  File "/__w/keylime/keylime/keylime/ima/ima.py", line 15, in <module>
    from keylime.ima.ima_schema import validate_runtime_policy
  File "/__w/keylime/keylime/keylime/ima/ima_schema.py", line 3, in <module>
    import jsonschema
  File "/tmp/keylime_test/lib64/python3.11/site-packages/jsonschema/__init__.py", line 23, in <module>
    from jsonschema.validators import (
  File "/tmp/keylime_test/lib64/python3.11/site-packages/jsonschema/validators.py", line 432, in <module>
    meta_schema=_utils.load_schema("draft3"),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/keylime_test/lib64/python3.11/site-packages/jsonschema/_utils.py", line 62, in load_schema
    return json.loads(data)
           ^^^^^^^^^^^^^^^^
  File "/__w/keylime/keylime/keylime/json.py", line 59, in loads
    return json_module.loads(s, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/__w/keylime/keylime/keylime/json.py", line 59, in loads
    return json_module.loads(s, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/__w/keylime/keylime/keylime/json.py", line 59, in loads
    return json_module.loads(s, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 944 more times]
RecursionError: maximum recursion depth exceeded

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>