Fix argv handling in main()
argv is not passed to main from entry_point which leads
to the following traceback:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_ima_emulator", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_ima_emulator')())
TypeError: main() missing 1 required positional argument: 'argv'

argv argument is not necessary as we can access sys.argv
directly.